### ISSUE TITLE
export fields should be read only

### ISSUE THREAD

**Issue by brugger** [usegalaxy-no/ansible-nels_storage#2]
It is possible to change the values of the two input boxes  "File path on NELS" and "NeLS id" the transfer crashes. If changing either of them the transfer fails

These should be made read-only instead

**Comment by kjetilkl** [comment]
I don't think it is possible to have read-only parameters in tool wrappers, but we could just hide them altogether. They are not really useful to display anyway.

**Comment by kjetilkl** [comment]
These two parameters have now been hidden
